# Generated by Django 4.2.7 on 2025-12-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='qr_uploads/')),
                ('decoded_text', models.TextField(blank=True)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('receiver', models.CharField(blank=True, max_length=200)),
                ('risk_level', models.CharField(choices=[('SAFE', 'Safe'), ('SCAM', 'Scam'), ('SUSPICIOUS', 'Suspicious')], default='SUSPICIOUS', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('ml_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
